# Generated by Django 5.1.3 on 2024-12-15 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='column',
            name='board',
        ),
        migrations.RemoveField(
            model_name='card',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='card',
            name='column',
        ),
        migrations.DeleteModel(
            name='Board',
        ),
        migrations.DeleteModel(
            name='Card',
        ),
        migrations.DeleteModel(
            name='Column',
        ),
    ]
